#!/usr/bin/env python
import os
import subprocess


db_name = os.getenv("DB_NAME")
db_base = os.getenv("DB_BASE")

# TODO activate only when we will have a real db
#if db_name:
#    for database in db_name.split(","):
#        subprocess.check_call(
#            ["click-odoo-update", "--if-exists", "-d", database, "--i18n-overwrite"]
#        )
