#!/bin/bash

if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" )" != '1' ]
then
    echo "Database does not exist, ignoring script"
    exit 0
fi

# TODO uncomment when queue_job will be installed

#echo "Resetting enqueued and started jobs to pending"
#psql --quiet << EOF
#  UPDATE queue_job SET state = 'pending' WHERE state in ('started', 'enqueued')
#EOF
